### ISSUE TITLE
src/ChainWalkContext.cpp:18:10: fatal error: 'openssl/rand.h' file not found

### ISSUE THREAD

**Issue by etr450b** [contact-discovery/rt_phone_numbers#2]
Hi!
Tried to install rt_phone_numbers but after doing : 
`brew install libomp` then `make -f Makefile.macOS`
I get the following error : 
`c++ -std=c++11 -Xpreprocessor -fopenmp -c src/ChainWalkContext.cpp -I/usr/local/include -O3 -o build/ChainWalkContext.o
src/ChainWalkContext.cpp:18:10: fatal error: 'openssl/rand.h' file not found
#include <openssl/rand.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/ChainWalkContext.o] Error 1`

Tried : 
- to reinstall openssl via brew
- to export variables after doing a `brew link openssl --force`

but nothing worked so far...

Running 11.3

Thanks !

**Comment by etr450b** [comment]
Still got the same issues after the modification.
Also tried to purge all and make a clean install but still...

**Comment by cwb38** [comment]
We checked the new version on multiple fresh machines and it seems to work out of the box. Maybe you can simply adjust the paths in the Makefile for your specific OpenSSL installation?

**Comment by etr450b** [comment]
Seems like the compiler ignored the `LDFLAGS` and `CXXFLAGS`...
Fixed the issue by creating symlinks : 
`ln -s /usr/local/opt/openssl@1.1/lib/* /usr/local/lib`
`ln -s /usr/local/opt/openssl@1.1/include/openssl/ /usr/local/include/`

Also faced `ld: library not found for -lgmp clang: error: linker command failed with exit code 1 (use -v to see invocation)` 

Fixed with (See: https://github.com/Homebrew/legacy-homebrew/issues/20041#issuecomment-18395843) : 
`brew uninstall gmp; brew install gmp`
`brew unlink gmp; brew link gmp`
